services:
  powerguardian-connector:
    image: ghcr.io/powerguardianos/connectoros-docker:latest
    ports:
      - "8090:8090"
    volumes:
      - ./data:/data
      - /etc/nut:/etc/nut
    restart: unless-stopped
